INSERT INTO LOCALES (VERSION, LANG_CODE, LANGUAGE, COUNTRY) VALUES (0,'EN','English','Great Britain');
INSERT INTO CONTACT_INFOS (ID, CITY, PHONE_NUMBER, ADDRESS) VALUES(1, 'Cracow', '12 396 61 11', 'Bora Komorowskiego 25C');
INSERT INTO CLUBS (NAME, CONTACT_INFOS_ID) VALUES('Bora Bora', 1);
INSERT INTO CLUB_LOCALS (REF_CLUB_ID, LANG_CODE, DESCRIPTION) VALUES(1, 'EN', 'Super Gym!');